# Site settings
title: About Comunic
email: contact@communiquons.org
description: Website about Comunic.

baseurl: "" # the subpath of your site, e.g. /blog/ (If you use organization leave empty)
url: "https://about.communiquons.org" # the base hostname & protocol for your site

#Comunic application URL
app_url: "http://devweb.local/comunic/v2/"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
# Build settings
