# Site settings
title: Comunic
email: contact@communiquons.org
description: Website about Comunic.

url: "https://about.communiquons.org"
baseurl: "" # the subpath of your site, e.g. /blog/ (If you use organization leave empty)

#Comunic application URL
app_url: "https://communiquons.org/"

#Comunic Android Application URL
play_store_url: "https://play.google.com/store/apps/details?id=org.communiquons.android.comunic.client"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
# Build settings
